import { boot, el, fields, button, empty } from './core.js';
import { chart, svg, transactions, money, moneyRows, monthRange, monthLabel, dataTable, addTransaction, sourceLink } from './viz.js';

boot({ id: 'income-expense-bars', title: 'Income & spending', symbol: '\u25a5', defaults: { months: 6, showNet: true }, configure: (r, c) => fields(r, c, [['months', 'Months', 'select', { options: [['3', '3'], ['6', '6'], ['12', '12']] }], ['showNet', 'Show monthly net', 'checkbox']]), render(app) {
  const r = app.root; r.replaceChildren(); const records = transactions(); const count = [3, 6, 12].includes(Number(app.config.months)) ? Number(app.config.months) : 6; const rows = moneyRows(records, monthRange(count)); r.append(el('p', 'A CLEARER VIEW OF CASH FLOW', 'eyebrow'));
  if (!rows.some(v => v.rows.length)) empty(r, 'No records in this period', 'Add a transaction or choose a longer period in Settings.');
  else {
    const latest = rows.at(-1), lead = el('div', undefined, 'chart-lead'), text = el('div'); text.append(el('p', 'This month', 'muted'), el('strong', money(latest.net)), el('p', 'Income minus spending', 'chart-note')); lead.append(text); r.append(lead);
    const surface = el('div', undefined, 'chart-surface'), view = chart(`Income and spending grouped bars over ${count} months`), left = 56, top = 20, bottom = 40, height = 260, width = 600, max = Math.max(1, ...rows.flatMap(row => [row.income, row.expense])); const plot = height - top - bottom; for (let n = 0; n <= 3; n++) { const y = top + plot * n / 3; view.append(svg('line', { x1: left, x2: width - 8, y1: y, y2: y, class: 'chart-grid' }), svg('text', { x: left - 6, y: y + 4, 'text-anchor': 'end', class: 'chart-axis' }, money(max * (3 - n) / 3, true))); }
    const groupWidth = (width - left - 8) / rows.length, bw = Math.min(22, groupWidth * .27); rows.forEach((row, i) => { const cx = left + groupWidth * (i + .5); for (const [kind, x] of [['income', cx - bw - 2], ['expense', cx + 2]]) { const amount = row[kind], bh = amount / max * plot; const rect = svg('rect', { x, y: top + plot - bh, width: bw, height: Math.max(0, bh), rx: 4, fill: kind === 'income' ? 'var(--primary)' : 'var(--accent)', class: 'bar-rect' }); rect.append(svg('title', {}, `${monthLabel(row.month)} ${kind}: ${money(amount)}`)); view.append(rect); } view.append(svg('text', { x: cx, y: height - 12, 'text-anchor': 'middle', class: 'chart-axis' }, count === 12 ? monthLabel(row.month).slice(0, 3) : monthLabel(row.month))); });
    surface.append(view); const legend = el('div', undefined, 'bar-legend'); for (const [name, color] of [['Income', 'var(--primary)'], ['Spending', 'var(--accent)']]) { const item = el('span', name); const mark = el('i', '', 'swatch'); mark.style.background = color; item.prepend(mark); legend.append(item); } r.append(surface, legend); if (app.config.showNet) { const nets = el('div', undefined, 'net-strip'); rows.forEach(row => { const n = el('div'); n.append(el('small', monthLabel(row.month)), el('strong', money(row.net, true))); nets.append(n); }); r.append(nets); } r.append(dataTable(['Month', 'Income', 'Spending', 'Net'], rows.map(row => [monthLabel(row.month), money(row.income), money(row.expense), money(row.net)])));
  }
  const actions = el('div', undefined, 'chart-actions'); actions.append(button('Add transaction', addTransaction, 'primary'), sourceLink('Open finance summary', '10-finance-summary')); r.append(actions);
} });
