export const day = (d = new Date()) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
export const date = s => new Date(s + 'T12:00:00');
export const validDate = s => typeof s === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(s) && !isNaN(date(s)) && day(date(s)) === s;
export function offset(s, n) { const d = date(s); d.setDate(d.getDate() + n); return day(d); }
const text = (v, max = 500) => typeof v === 'string' && v.length <= max;
const identifier = v => text(v, 100) && v.length > 0;
const uniqueIds = a => a.every(v => v && typeof v === 'object') && new Set(a.map(v => v.id)).size === a.length;
export const validEvents = a => Array.isArray(a) && a.length <= 10000 && uniqueIds(a) && a.every(v => v && identifier(v.id) && text(v.title, 120) && v.title.trim() && validDate(v.date) && (v.time === '' || /^([01]\d|2[0-3]):[0-5]\d$/.test(v.time)) && text(v.category, 50) && text(v.notes, 1000));
export function sortedEvents(a, start, end = '9999-12-31') { return a.filter(e => e.date >= start && e.date <= end).sort((a, b) => (a.date + a.time).localeCompare(b.date + b.time)); }
export const validHabits = a => Array.isArray(a) && a.length <= 100 && uniqueIds(a) && a.every(v => v && identifier(v.id) && text(v.name, 120) && v.name.trim() && Array.isArray(v.days) && v.days.length <= 100000 && v.days.every(validDate));
export function streak(days, today = day()) { const set = new Set(days); let cursor = set.has(today) ? today : offset(today, -1); let n = 0; while (set.has(cursor)) { n++; cursor = offset(cursor, -1); } return n; }
export function bestStreak(days) { const sorted = [...new Set(days)].sort(); let best = 0, run = 0, prev = ''; for (const d of sorted) { run = prev && offset(prev, 1) === d ? run + 1 : 1; best = Math.max(best, run); prev = d; } return best; }
export const validTransactions = a => Array.isArray(a) && a.length <= 20000 && uniqueIds(a) && a.every(v => v && identifier(v.id) && validDate(v.date) && text(v.label, 120) && v.label.trim() && Number.isFinite(v.amount) && v.amount > 0 && v.amount <= 1e12 && ['income', 'expense'].includes(v.type) && text(v.category, 50));
export function totals(records, month) { const rows = records.filter(r => r.date.slice(0, 7) === month); const income = rows.filter(r => r.type === 'income').reduce((a, b) => a + b.amount, 0); const expense = rows.filter(r => r.type === 'expense').reduce((a, b) => a + b.amount, 0); return { income, expense, net: income - expense, rows }; }
export const validFocus = o => o && typeof o === 'object' && !Array.isArray(o) && Object.entries(o).length <= 10000 && Object.entries(o).every(([k, v]) => validDate(k) && v && text(v.goal, 500) && text(v.notes, 2000) && Array.isArray(v.tasks) && v.tasks.length <= 100 && uniqueIds(v.tasks) && v.tasks.every(t => t && identifier(t.id) && text(t.text, 200) && typeof t.done === 'boolean'));
export const validLinks = a => Array.isArray(a) && a.length <= 100 && uniqueIds(a) && a.every(v => { if (!v || !identifier(v.id) || !text(v.name, 100) || !v.name.trim() || !text(v.url, 2000)) return false; try { return ['http:', 'https:'].includes(new URL(v.url).protocol); } catch { return false; } });
export const validSkin = o => o && typeof o === 'object' && !Array.isArray(o) && Object.keys(o).length <= 20000 && Object.entries(o).every(([k, v]) => /^\d{4}-\d{2}-\d{2}:(am|pm)$/.test(k) && validDate(k.slice(0, 10)) && v && text(v.notes, 2000) && Array.isArray(v.steps) && v.steps.length <= 30 && v.steps.every(s => text(s, 100) && s.trim()) && new Set(v.steps).size === v.steps.length && Array.isArray(v.done) && new Set(v.done).size === v.done.length && v.done.every(s => v.steps.includes(s)));
