import { boot, el, fields, button, empty, localDay, progress } from './core.js';
import { allHabits, habitRate, dataTable, sourceLink } from './viz.js';
import { streak } from './logic.js';
import { editHabit, toggleHabit } from './habits.js';

boot({ id: 'habit-progress-bars', title: 'Habit progress', symbol: '\u25a4', defaults: { days: 30, sort: 'rate', limit: 10 }, configure: (r, c) => fields(r, c, [['days', 'Period', 'select', { options: [['7', '7 days'], ['30', '30 days'], ['90', '90 days']] }], ['sort', 'Sort habits', 'select', { options: [['rate', 'Completion rate'], ['streak', 'Current streak'], ['name', 'Name']] }], ['limit', 'Habits to show', 'number', { min: 1, max: 100 }]]), render(app) {
  const r = app.root; r.replaceChildren(); const today = localDay(), count = [7, 30, 90].includes(Number(app.config.days)) ? Number(app.config.days) : 30; const rows = allHabits().map(h => ({ habit: h, ...habitRate(h, today, count), streak: streak(h.days, today) })); if (app.config.sort === 'name') rows.sort((a, b) => a.habit.name.localeCompare(b.habit.name)); else if (app.config.sort === 'streak') rows.sort((a, b) => b.streak - a.streak); else rows.sort((a, b) => b.percent - a.percent);
  r.append(el('p', `THE LAST ${count} DAYS`, 'eyebrow')); if (!rows.length) empty(r, 'Momentum builds with each day', 'Add a habit and check it off to start this chart.');
  else {
    const avg = Math.round(rows.reduce((sum, row) => sum + row.percent, 0) / rows.length); const lead = el('div', undefined, 'chart-lead'), text = el('div'); text.append(el('strong', avg + '%'), el('p', 'Average completion', 'muted')); lead.append(text, el('span', `${rows.length} daily ${rows.length === 1 ? 'habit' : 'habits'}`, 'tag')); r.append(lead);
    const list = el('div', undefined, 'bar-list'); rows.slice(0, Math.max(1, Math.min(100, app.config.limit))).forEach((row, i) => { const card = el('article', undefined, 'habit-bar-card'); const heading = el('div', undefined, 'bar-heading'); heading.append(el('strong', row.habit.name), el('span', `${row.percent}%`, 'bar-percent')); card.append(heading); const track = progress(row.percent, `${row.habit.name}: ${row.completed} of ${count} days`); track.classList.add('animated-track'); track.style.setProperty('--delay', i * 55 + 'ms'); card.append(track); const footer = el('div', undefined, 'bar-footer'); footer.append(el('span', `${row.completed}/${count} days / ${row.streak} day streak`, 'muted small'), button(row.habit.days.includes(today) ? 'Checked today' : 'Check in', () => toggleHabit(row.habit.id), row.habit.days.includes(today) ? 'quiet' : 'primary')); card.append(footer); list.append(card); }); r.append(list, dataTable(['Habit', 'Completed days', 'Rate', 'Current streak'], rows.map(row => [row.habit.name, `${row.completed}/${count}`, row.percent + '%', row.streak])));
  }
  const actions = el('div', undefined, 'chart-actions'); actions.append(button('Add habit', () => editHabit(), 'primary'), sourceLink('Open habit summary', '11-habit-summary')); r.append(actions);
} });
