import { boot, read, save, el, field, button, dialog, submit, uid, localDay, progress, confirmDelete, datasetTools } from './core.js';
import { validFocus } from './logic.js';
let selected = localDay(); const records = () => { const v = read('focus', {}); return validFocus(v) ? v : {}; };
boot({ id: 'focus', title: "Today's focus", symbol: '\u25ce', render(app) {
  const r = app.root; r.replaceChildren(); const all = records(), entry = all[selected] || { goal: '', notes: '', tasks: [] }; const write = next => save('focus', { ...records(), [selected]: next });
  const date = field('Day', selected, 'date', { required: true }); date.control.onchange = () => { if (date.value()) { selected = date.value(); app.redraw(); } }; r.append(date);
  r.append(el('p', 'ONE THING THAT MATTERS', 'eyebrow'), el('h2', entry.goal || 'Choose your focus', 'focus-goal'));
  r.append(button(entry.goal ? 'Edit focus & notes' : 'Set daily focus', () => dialog('Daily focus', (f, close) => { const goal = field('Main focus', entry.goal, 'textarea', { maxlength: 500 }); const notes = field('Notes', entry.notes, 'textarea', { maxlength: 2000 }); f.append(goal, notes); submit(f, 'Save focus', () => { write({ ...entry, goal: goal.value(), notes: notes.value() }); close(); }); })));
  if (entry.notes) r.append(el('p', entry.notes, 'notes')); const complete = entry.tasks.filter(v => v.done).length; r.append(progress(entry.tasks.length ? complete / entry.tasks.length * 100 : 0, 'Tasks completed'), el('p', `${complete} of ${entry.tasks.length} tasks completed`, 'muted small'));
  entry.tasks.forEach(t => { const row = el('div', undefined, 'record'); const box = field(t.text, t.done, 'checkbox'); box.classList.add('check-row', 'grow'); box.control.onchange = () => write({ ...entry, tasks: entry.tasks.map(v => v.id === t.id ? { ...v, done: box.value() } : v) }); row.append(box, button('Edit', () => dialog('Edit task', (f, close) => { const input = field('Task', t.text, 'text', { required: true, maxlength: 200 }); f.append(input); submit(f, 'Save task', () => { if (!input.value().trim()) throw Error('Enter a task.'); write({ ...entry, tasks: entry.tasks.map(v => v.id === t.id ? { ...v, text: input.value().trim() } : v) }); close(); }); }), 'quiet'), button('Delete', () => confirmDelete(t.text, () => write({ ...entry, tasks: entry.tasks.filter(v => v.id !== t.id) })), 'quiet')); r.append(row); });
  r.append(button('Add task', () => dialog('Add task', (f, close) => { const input = field('Task', '', 'text', { required: true, maxlength: 200 }); f.append(input); submit(f, 'Add task', () => { if (!input.value().trim()) throw Error('Enter a task.'); if (entry.tasks.length >= 100) throw Error('Maximum 100 tasks per day.'); write({ ...entry, tasks: [...entry.tasks, { id: uid(), text: input.value().trim(), done: false }] }); close(); }); }), 'primary')); datasetTools(r, 'focus', records, validFocus, v => save('focus', v));
} });
