import { boot, read, save, el, field, fields, button, dialog, submit, uid, localDay, metric, progress, empty, confirmDelete, datasetTools } from './core.js';
import { totals, validTransactions } from './logic.js';
let month = localDay().slice(0, 7), page = 0;
const transactions = () => { const v = read('transactions', []); return validTransactions(v) ? v : []; };
function edit(item) { dialog(item ? 'Edit transaction' : 'Add transaction', (f, close) => { const label = field('Description', item?.label || '', 'text', { required: true, maxlength: 120 }); const amount = field('Amount', item?.amount || '', 'number', { required: true, min: 0.01, max: 1e12, step: 'any' }); const type = field('Type', item?.type || 'expense', 'select', { options: ['expense', 'income'] }); const date = field('Date', item?.date || localDay(), 'date', { required: true }); const category = field('Category', item?.category || 'Other', 'text', { maxlength: 50 }); f.append(label, amount, type, date, category); submit(f, 'Save transaction', () => { const record = { id: item?.id || uid(), label: label.value().trim(), amount: Number(amount.value()), type: type.value(), date: date.value(), category: category.value().trim() || 'Other' }; if (!validTransactions([record])) throw Error('Enter a description, date, and positive amount.'); const rows = transactions().filter(v => v.id !== record.id); rows.push(record); save('transactions', rows); close(); }); }); }
boot({ id: 'finance', title: 'Finance summary', symbol: '\u25c8', defaults: { currency: 'INR', budget: 0, opening: 0, limit: 5 }, configure: (r, c) => { const get = fields(r, c, [['currency', 'Currency code (for example INR, USD)', 'text', { maxlength: 3, pattern: '[A-Za-z]{3}' }], ['budget', 'Monthly spending budget (0 disables)', 'number', { min: 0, max: 1e12, step: 'any' }], ['opening', 'Opening balance for selected month', 'number', { min: -1e12, max: 1e12, step: 'any' }], ['limit', 'Recent records to display', 'number', { min: 1, max: 100 }]]); r.append(el('p', 'Budget and opening balance apply to the selected month. Changing currency changes the label; it does not convert amounts.', 'muted small')); return () => { const next = get(); new Intl.NumberFormat(undefined, { style: 'currency', currency: next.currency }); const budgets = read('finance-months', {}); save('finance-months', { ...budgets, [month]: { budget: next.budget, opening: next.opening } }); return { currency: next.currency.toUpperCase(), limit: next.limit }; }; }, render(app) {
  const r = app.root; r.replaceChildren(); const budgetMap = read('finance-months', {}), cfg = { ...app.config, ...(budgetMap[month] || { budget: 0, opening: 0 }) }; app.config.budget = cfg.budget; app.config.opening = cfg.opening;
  let formatter; try { formatter = new Intl.NumberFormat(undefined, { style: 'currency', currency: cfg.currency, maximumFractionDigits: 2 }); } catch { formatter = new Intl.NumberFormat(undefined, { style: 'currency', currency: 'INR' }); } const money = n => formatter.format(n);
  const pick = field('Month', month, 'month', { required: true }); pick.control.onchange = () => { if (pick.value()) { month = pick.value(); app.redraw(); } }; r.append(pick); const all = transactions(), data = totals(all, month);
  r.append(el('p', 'MONTH BALANCE', 'eyebrow'), el('div', money(Number(cfg.opening) + data.net), 'hero balance')); const metrics = el('div', undefined, 'metrics'); metric(metrics, money(data.income), 'Income'); metric(metrics, money(data.expense), 'Spent'); metric(metrics, money(data.net), 'Net this month'); r.append(metrics);
  if (cfg.budget > 0) { r.append(el('p', `${money(data.expense)} of ${money(cfg.budget)} budget`, 'muted'), progress(data.expense / cfg.budget * 100, 'Monthly budget used'), el('p', money(Math.abs(cfg.budget - data.expense)) + (data.expense > cfg.budget ? ' over budget' : ' available'), data.expense > cfg.budget ? 'notice error' : 'small muted')); } else r.append(el('p', 'Set a monthly budget in Settings to see your budget progress.', 'small muted'));
  const categories = new Map(); data.rows.filter(v => v.type === 'expense').forEach(v => categories.set(v.category, (categories.get(v.category) || 0) + v.amount)); if (categories.size) r.append(el('h3', 'Spending by category')); [...categories].sort((a, b) => b[1] - a[1]).forEach(([name, amount]) => { r.append(el('p', name + ' / ' + money(amount), 'small'), progress(amount / data.expense * 100, name)); });
  r.append(button('Add transaction', () => edit(), 'primary'), el('h3', 'Recent transactions')); if (!data.rows.length) empty(r, 'A fresh page', 'Add income or an expense to begin.'); const sorted = [...data.rows].sort((a, b) => b.date.localeCompare(a.date)); const size = Math.max(1, Math.min(100, cfg.limit)); const pages = Math.max(1, Math.ceil(sorted.length / size)); page = Math.min(page, pages - 1); const shown = sorted.slice(page * size, (page + 1) * size); shown.forEach(t => { const row = el('article', undefined, 'record'), details = el('div', undefined, 'grow'); details.append(el('strong', t.label), el('p', `${t.date} / ${t.category}`, 'small muted'), el('span', (t.type === 'income' ? '+' : '-') + money(t.amount), 'amount')); row.append(details, button('Edit', () => edit(t), 'quiet'), button('Delete', () => confirmDelete(t.label, () => save('transactions', transactions().filter(v => v.id !== t.id))), 'quiet')); r.append(row); }); if (pages > 1) { const nav = el('div', undefined, 'actions'); const previous = button('Previous records', () => { page--; app.redraw(); }); previous.disabled = page === 0; const next = button('Next records', () => { page++; app.redraw(); }); next.disabled = page === pages - 1; nav.append(previous, el('span', `Page ${page + 1} of ${pages}`, 'small muted'), next); r.append(nav); }
  datasetTools(r, 'finances', () => ({ transactions: transactions(), months: read('finance-months', {}) }), v => v && validTransactions(v.transactions) && v.months && typeof v.months === 'object' && !Array.isArray(v.months) && Object.entries(v.months).every(([k, x]) => /^\d{4}-(0[1-9]|1[0-2])$/.test(k) && x && Number.isFinite(x.budget) && x.budget >= 0 && x.budget <= 1e12 && Number.isFinite(x.opening) && Math.abs(x.opening) <= 1e12), v => { save('transactions', v.transactions); save('finance-months', v.months); });
} });
