import { boot, el, fields, button, dialog, field, submit, clamp, progress } from './core.js';

function valid(next) { if (!next.name.trim()) throw Error('Enter a goal name.'); if (!Number.isFinite(next.target) || next.target <= 0 || next.target > 1e9) throw Error('Target must be greater than zero.'); if (!Number.isFinite(next.current) || next.current < 0 || next.current > 1e9) throw Error('Current value must be zero or greater.'); if (!Number.isFinite(next.step) || next.step <= 0 || next.step > 1e9) throw Error('Step must be greater than zero.'); return { ...next, name: next.name.slice(0, 80), unit: next.unit.slice(0, 24) }; }
const app = boot({ id: 'goal-orb', title: 'Goal progress', symbol: '\u25ce', defaults: { name: 'Next milestone', current: 0, target: 100, unit: 'steps', step: 1, motion: true, depth: true }, configure: (r, c) => { const get = fields(r, c, [['name', 'Goal name', 'text', { maxlength: 80, required: true }], ['current', 'Current value', 'number', { min: 0, max: 1e9, step: 'any' }], ['target', 'Target value', 'number', { min: .01, max: 1e9, step: 'any' }], ['unit', 'Unit label', 'text', { maxlength: 24 }], ['step', 'Quick change amount', 'number', { min: .01, max: 1e9, step: 'any' }], ['motion', 'Animate progress', 'checkbox'], ['depth', 'Use 3D depth', 'checkbox']]); return () => valid(get()); }, render(app) {
  const r = app.root; r.replaceChildren(); const c = app.config, target = Number(c.target) > 0 ? Number(c.target) : 100, current = Math.max(0, Number(c.current) || 0), exact = Math.round(current / target * 100), shown = clamp(exact, 0, 100), number = n => new Intl.NumberFormat(undefined, { maximumFractionDigits: 2 }).format(n);
  r.append(el('p', 'ONE STEP AT A TIME', 'eyebrow'), el('h2', c.name, 'goal-name'));
  const scene = el('div', undefined, 'goal-scene'); scene.dataset.depth = String(c.depth); scene.dataset.motion = String(c.motion); const orb = el('div', undefined, 'goal-orb'); orb.style.setProperty('--value', shown + '%'); orb.style.setProperty('--fill', shown + '%'); orb.setAttribute('role', 'img'); orb.setAttribute('aria-label', `${c.name}: ${number(current)} of ${number(target)} ${c.unit}, ${exact} percent`); const rim = el('div', undefined, 'goal-rim'); rim.append(el('span', exact + '%', 'goal-percent'), el('span', 'COMPLETE', 'goal-subtitle')); orb.append(rim); scene.append(orb); r.append(scene);
  const stats = el('div', undefined, 'goal-stats'); stats.append(el('span', `Current: ${number(current)}`), el('span', `Target: ${number(target)} ${c.unit}`)); r.append(stats, progress(shown, c.name + ' progress'));
  const change = delta => app.setConfig({ current: Math.min(1e9, Math.max(0, Math.round((current + delta) * 1e6) / 1e6)) }); const actions = el('div', undefined, 'goal-actions'); actions.append(button('- ' + number(c.step), () => change(-Number(c.step))), button('+ ' + number(c.step), () => change(Number(c.step)), 'primary'), button('Set value', () => dialog('Set goal progress', (form, close) => { const value = field('Current value', current, 'number', { min: 0, max: 1e9, step: 'any', required: true }); form.append(value); submit(form, 'Save progress', () => { const n = Number(value.value()); if (!Number.isFinite(n) || n < 0 || n > 1e9) throw Error('Enter a valid nonnegative number.'); app.setConfig({ current: n }); close(); }); }))); r.append(actions);
  if (current >= target) r.append(el('p', 'Milestone reached. You can keep counting beyond the target.', 'muted small')); r.append(el('p', 'Create another embed with a different ?id= value for a separate goal.', 'muted small'));
} });
