import { boot, read, save, el, field, fields, button, localDay, progress, empty, dialog, submit, confirmDelete, datasetTools } from './core.js';
import { validSkin } from './logic.js';
let selected = localDay(), session = new Date().getHours() < 16 ? 'am' : 'pm';
const records = () => { const v = read('skin', {}); return validSkin(v) ? v : {}; };
const steps = value => [...new Set(String(value).split('\n').map(s => s.trim().slice(0, 100)).filter(Boolean))].slice(0, 30);
boot({ id: 'skin', title: 'Skin-care routine', symbol: '\u273f', defaults: { am: '', pm: '' }, configure: (r, c) => { r.append(el('p', 'Enter your own routine, one step per line. Changing a routine affects new sessions; saved history keeps its original steps.', 'muted')); return fields(r, c, [['am', 'Morning routine (one step per line)', 'textarea', { maxlength: 3000 }], ['pm', 'Evening routine (one step per line)', 'textarea', { maxlength: 3000 }]]); }, render(app) {
  const r = app.root; r.replaceChildren(); const date = field('Routine date', selected, 'date', { max: localDay(), required: true }); date.control.onchange = () => { if (date.value() && date.value() <= localDay()) { selected = date.value(); app.redraw(); } }; r.append(date);
  const tabs = el('div', undefined, 'tabs'); for (const [id, label] of [['am', 'Morning'], ['pm', 'Evening']]) { const b = button(label, () => { session = id; app.redraw(); }, session === id ? 'primary' : ''); b.setAttribute('aria-pressed', id === session); tabs.append(b); } r.append(tabs);
  const key = selected + ':' + session, all = records(); const current = all[key] || { steps: steps(app.config[session]), done: [], notes: '' }; const write = value => save('skin', { ...records(), [key]: value }); const pct = current.steps.length ? Math.round(current.done.length / current.steps.length * 100) : 0;
  r.append(el('p', session === 'am' ? 'A FRESH START' : 'TIME TO UNWIND', 'eyebrow'), el('h2', `${current.done.length} / ${current.steps.length} steps complete`), progress(pct, 'Routine progress'));
  if (!current.steps.length) empty(r, 'Your routine, your pace', 'Open Settings to add your morning and evening steps.'); current.steps.forEach((name, index) => { const row = el('div', undefined, 'skin-step'); row.append(el('span', String(index + 1).padStart(2, '0'), 'step-number')); const check = field(name, current.done.includes(name), 'checkbox'); check.classList.add('check-row', 'grow'); check.control.onchange = () => write({ ...current, done: check.value() ? [...current.done, name] : current.done.filter(v => v !== name) }); row.append(check); r.append(row); });
  if (current.steps.length) r.append(button(pct === 100 ? 'Clear session check-ins' : 'Complete routine', () => pct === 100 ? confirmDelete('check-ins for this session', () => write({ ...current, done: [] })) : write({ ...current, done: [...current.steps] }), pct === 100 ? '' : 'primary'));
  r.append(button('Session notes', () => dialog('Skin-care notes', (f, close) => { const notes = field('Notes', current.notes, 'textarea', { maxlength: 2000 }); f.append(notes); submit(f, 'Save notes', () => { write({ ...current, notes: notes.value() }); close(); }); })));
  if (current.notes) r.append(el('p', current.notes, 'notes')); if (all[key]) r.append(button('Use updated routine for this session', () => confirmDelete('the saved step list for this session', () => write({ steps: steps(app.config[session]), done: [], notes: current.notes })), 'quiet'));
  r.append(el('p', 'A personal routine log. No product or treatment recommendations are supplied.', 'muted small')); datasetTools(r, 'skin-care', records, validSkin, v => save('skin', v));
} });
